# Generated by Django 4.2.28 on 2026-02-25 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('REGI_CLOSED', 'Regi Closed'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='WAITING', max_length=20)),
                ('max_entries', models.PositiveIntegerField()),
                ('max_reentries', models.PositiveIntegerField(default=0)),
                ('registration_deadline', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('starting_chips', models.PositiveIntegerField()),
                ('reentry_chips', models.PositiveIntegerField()),
                ('addon_chips', models.PositiveIntegerField()),
                ('max_addons', models.PositiveIntegerField(default=0)),
                ('blind_structure', models.JSONField()),
                ('prize_structure', models.JSONField()),
                ('buy_in_amount', models.PositiveIntegerField()),
                ('addon_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_entries_cache', models.PositiveIntegerField(default=0)),
                ('total_reentries_cache', models.PositiveIntegerField(default=0)),
                ('total_addons_cache', models.PositiveIntegerField(default=0)),
                ('live_players_cache', models.PositiveIntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='shops.shop')),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_images',
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('BUSTED', 'Busted'), ('CANCELED', 'Canceled')], default='REGISTERED', max_length=20)),
                ('total_entries_cache', models.PositiveIntegerField(default=1)),
                ('total_reentries_cache', models.PositiveIntegerField(default=0)),
                ('total_addons_cache', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('busted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_entries',
            },
        ),
        migrations.CreateModel(
            name='BuyInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTRY', 'Entry'), ('REENTRY', 'Reentry'), ('ADDON', 'Addon')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyin_events', to='tournaments.tournamententry')),
            ],
            options={
                'db_table': 'buy_in_events',
            },
        ),
        migrations.AddIndex(
            model_name='tournamententry',
            index=models.Index(fields=['tournament'], name='tournament__tournam_aa427f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamententry',
            index=models.Index(fields=['player'], name='tournament__player__470b9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamententry',
            unique_together={('player', 'tournament')},
        ),
        migrations.AddIndex(
            model_name='buyinevent',
            index=models.Index(fields=['entry', 'type'], name='buy_in_even_entry_i_c2136e_idx'),
        ),
    ]
