# Generated by Django 4.2.28 on 2026-07-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamententry_seat_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='buy_in_amount',
            new_name='entry_fee',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='max_entries',
            new_name='max_participants',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='addon_amount',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='addon_chips',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='blind_structure',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='early_chips',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_addons',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_reentries',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='reentry_chips',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='starting_chips',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_addons_cache',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_entries_cache',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_reentries_cache',
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('POKER', 'Poker'), ('CHESS', 'Chess'), ('POKEMON_TCG', 'Pokémon TCG')], default='POKER', max_length=30),
        ),
        migrations.CreateModel(
            name='PokerTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_entries', models.PositiveIntegerField()),
                ('max_reentries', models.PositiveIntegerField(default=0)),
                ('max_addons', models.PositiveIntegerField(default=0)),
                ('starting_chips', models.PositiveIntegerField()),
                ('early_chips', models.PositiveIntegerField(default=0)),
                ('reentry_chips', models.PositiveIntegerField()),
                ('addon_chips', models.PositiveIntegerField()),
                ('blind_structure', models.JSONField()),
                ('addon_amount', models.PositiveIntegerField()),
                ('total_entries_cache', models.PositiveIntegerField(default=0)),
                ('total_reentries_cache', models.PositiveIntegerField(default=0)),
                ('total_addons_cache', models.PositiveIntegerField(default=0)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poker_tournament', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'poker_tournaments',
            },
        ),
    ]
