# Generated by Django 4.2.28 on 2026-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_rename_buy_in_amount_tournament_entry_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokertournament',
            name='addon_amount',
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='addon_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='reentry_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
