# Generated by Django 4.2.28 on 2026-07-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_pokertournament_addon_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinevent',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyinevent',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
